### ISSUE TITLE
some modules are not found

### ISSUE THREAD

**Issue by TukulHX** [cure-lab/ContraNet#4]
Hello author, I have some questions while I try to replicate your result. For example, "import lib.pytorch_ssim as ssim_package" is't a package, so "import lib.pytorch_ssim as ssim_package" is't correct. And I found nothing with "from adaptiveCWattackl2 import CarliniWagnerL2Attack". Could you please provide the complete code? Thanks a lot.

**Comment by yangyijune** [comment]
Thanks for your information. The missing `adaptiveCWattackl2.py` file has been uploaded. The `pytorch_ssim` is a package. Just install the package `pip install pytorch_ssim` and `import pytorch_ssim as ssim_package`.
